clean up bash_prompt.sh

diff --git a/bash_prompt b/bash_prompt
--- a/bash_prompt
+++ b/bash_prompt
@@ -1,25 +1,29 @@
-#! /bin/bash
+#!/bin/bash
 setup_prompt(){
-  # PROMPT_DIRRIM is used as the number of trailing directory components to retain
-  # when expanding the \w and \W prompt string escapes
-  export PROMPT_DIRTRIM=4
-  local -r ps_clear="\[\033[0m\]"
-  local -r red="\[\033[0;31m\]"
-  local -r yellow="\[\033[0;33m\]"
-  local -r green="\[\033[0;32m\]"
-  local -r purple="\[\033[0;35m\]"
-  local -r blue="\[\033[0;34m\]"
-  local -r white="\[\033[0;37m\]"
-  #NOTE $ has to be escaped to avoid subshells' immediate evaluation
-  local -r exit_code="\$(c=\$?; [[ \$c == 0 ]] && echo \"${green}[+]\" || echo \"${red}[-]\")"
-  local -r fqdn="\$(hostname --fqdn)"
-  local -r user="\$(whoami)"
-  local -r git_branch=" \$(which git >/dev/null && git branch 2>/dev/null | grep '*' | sed 's/* \(.*\)/(\1)/')"
-  local -r pwd_color="\$( if [[ $fqdn =~ jupiter|neptune|imac-amir ]]; then echo \"${purple}\";else echo \"${yellow}\"; fi)"
-  #NOTE if user is root make cursor red
-  local -r user_color="\$( [[ $user == 'root' ]] && echo \"${red}\" )"
+  # color codes
+  declare -r ps_clear="\[\033[0m\]"
+  declare -r red="\[\033[0;31m\]"
+  declare -r yellow="\[\033[0;33m\]"
+  declare -r green="\[\033[0;32m\]"
+  declare -r purple="\[\033[0;35m\]"
+  declare -r blue="\[\033[0;34m\]"
+  declare -r white="\[\033[0;37m\]"
 
-  local -r memory_usage="\$(awk '/MemTotal/{t=\$2};/MemFree/{f=\$2};END {printf \"%.2f%%\", (t-f)*100/t}' /proc/meminfo)"
-  local -r disk_usage="\$(df --total -h | tail -n 1 | awk '{ print \$5}')"
+  # number of trailing directory components retained when expanding \w and \W
+  # see https://www.gnu.org/software/bash/manual/bashref.html
+  export PROMPT_DIRTRIM=4
+
+  declare -r fqdn=$(hostname --fqdn)
+  declare -r user=$(whoami)
+  declare -r git_branch=" \$(which git >/dev/null && git branch 2>/dev/null | grep '*' | sed 's/* \(.*\)/(\1)/')"
+  # if current machine is not mine show the current directory in purple
+  declare -r pwd_color="$( [[ $fqdn =~ mars|jupiter|neptune|imac-amir ]] && echo ${blue} || echo ${purple} )"
+  # if user is root show user in red
+  declare -r user_color="$( [[ $user == 'root' ]] && echo ${red} || echo ${blue})"
+  # show [-]/[+] for previous command's exit code, note that
+  # exit_codes must be re-evaluated everytime PS1 is evaluated,
+  # escape $ to avoid subshells' immediate evaluation.
+  declare -r exit_code="\$(c=\$?; [[ \$c == 0 ]] && echo \"${green}[+]\" || echo \"${red}[-]\")"
+
   export PS1="${exit_code}${white}${user_color}${user}${white}@${fqdn}:${pwd_color}\w${green}${git_branch}${pwd_color} > ${ps_clear}"
 }
