more fixups for rcup.sh

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,9 @@
 #!/bin/bash
-
+set -e
 set -u
+
+log(){ printf -- "---> $1\n" >&2; }
+
 # find the real username and home directory in case this is a non-login shell,
 # e.g. in a docker build.
 USER=$( whoami )
@@ -14,9 +17,6 @@ else
   RCUP=$CUR_DIR/rcup.sh
 fi
 RCUP_OPTS="-f -v -d '$CUR_DIR' -x install -x README.md -x rcup.sh"
-
-
-log(){ printf -- "---> $1\n" >&2; }
 
 privileged(){
   if [ $USER = root ]; then
@@ -85,8 +85,10 @@ main(){
         log 'rcm needs to be installed to generate standalone scripts'
         return 1
       fi
-      # for some reason fails unless it's in bash -c!
-      bash -c "rcup $RCUP_OPTS -g" > $1
+      # 1. for some reason fails unless it's in bash -c!
+      # 2. don't evaluate HOME here, let it be evaluated where we run rcup.sh
+      # 3. don't hardcode the PWD here, let it remain relative
+      HOME='$HOME' bash -c "rcup $RCUP_OPTS -g" | sed "s|$(readlink -f $CUR_DIR)/||" > $1
       return $?
       ;;
     pubkey)
